#ifndef __ST_VEC3F_H__
#define __ST_VEC3F_H__

//Why make this a class and not a struct? Well, for one, I think it should eventually be able to do some vector calculations.
//For now, it's just a pretty dumb container. To the point where most of the functions would be autogenerated in some languages, in fact.

class STVec3f
{
private:
	float x;
	float y;
	float z;
public:
	STVec3f(float x, float y, float z);
	STVec3f() : STVec3f(0.0f, 0.0f, 0.0f) {};
	
	float getX() {return this->x;};
	float getY() {return this->y;};
	float getZ() {return this->z;};

	void setX(float x) {this->x = x;};
	void setY(float y) {this->y = y;};
	void setZ(float z) {this->z = z;};
	
	void addX(float x) {this->x += x;};
	void addY(float y) {this->y += y;};
	void addZ(float z) {this->z += z;};
	
	void mulX(float scale) {this->x *= scale;};
	void mulY(float scale) {this->y *= scale;};
	void mulZ(float scale) {this->z *= scale;};

};


#endif //__ST_VEC3F_H__
